game: game.h Bomba.h Funcoes.h Bomber.h Fire.h Wall.h WoodBox.h Explosion.h Dog.h Explosion2.h Caveira1.h Genericas.h Fogo.h menux.c
	gcc menux.c -o menux -Wall `sdl-config --cflags --libs` -lSDL_mixer -lSDL_image

depurando:
	gcc menux.c -o menux -Wall `sdl-config --cflags --libs` -lSDL_mixer -lSDL_image -g

limpa:
	rm game
