sudo: require
language: cpp
compiler: gcc
# dist: trusty # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109

addons: 
  apt: 
    packages: libboost-all-dev

before_install:
  # Qt5, from https://gist.github.com/jreese/6207161#gistcomment-1462109
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq

install:
 - sudo apt-get install -qq librapidxml-dev libsdl2-mixer-dev libdevil-dev

# Start virtual X server, from https://docs.travis-ci.com/user/gui-and-headless-browsers/
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
 - qmake
 - make
 - ./Mario
